/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	//ajout tme4
	result = argp->operand1 + argp->operand2;

	return &result;
}
